services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=http://${HOST_IP} #optional
    volumes:
      - ${CONFIG_BASE}/jellyfin:/config
      - ${MEDIA_PATH}:/mnt/media
    devices:
      - /dev/dri:/dev/dri #Use for Intel QuickSync
    ports:
      - ${HOST_IP}:${JELLYFIN_PORT}:8096
      - ${HOST_IP}:${JELLYFIN_DISCOVERY_UDP}:7359/udp #Service Discovery
      - ${HOST_IP}:${JELLYFIN_DLNA_UDP}:1900/udp #Client Discovery
    restart: "on-failure:${RESTART_MAX_RETRIES:-5}"
    labels:
      - "io.portainer.webui=http://${HOST_IP}:${JELLYFIN_PORT:-8096}"
      - icon=https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/jellyfin.png
# Remove the Jellyfin service if installed directly on system.

  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_BASE}/jellyseerr:/app/config
    ports:
      - ${HOST_IP}:${JELLYSEERR_PORT}:5055
    restart: "on-failure:${RESTART_MAX_RETRIES:-5}"
    labels:
      - "io.portainer.webui=http://${HOST_IP}:${JELLYSEERR_PORT:-5055}"
      - icon=https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/jellyseerr.png

  jellystat-db:
    image: postgres:15.2
    container_name: jellystat-db
    restart: "on-failure:${RESTART_MAX_RETRIES:-5}"
    environment:
      POSTGRES_USER: ${JELLYSTAT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${JELLYSTAT_POSTGRES_PASSWORD}
    volumes:
      - ${CONFIG_BASE}/jellystat/postgres:/var/lib/postgresql/data

  jellystat:
    image: cyfershepard/jellystat:latest
    container_name: jellystat
    restart: "on-failure:${RESTART_MAX_RETRIES:-5}"
    labels:
      - "io.portainer.webui=http://${HOST_IP}:${JELLYSTAT_PORT:-3000}"
      - icon=https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/jellystat.png
    environment:
      POSTGRES_USER: ${JELLYSTAT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${JELLYSTAT_POSTGRES_PASSWORD}
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: ${JELLYSTAT_JWT_SECRET}
      TZ: ${TZ}
    volumes:
      - ${CONFIG_BASE}/jellystat/backup-data:/app/backend/backup-data
    ports:
      - ${HOST_IP}:${JELLYSTAT_PORT}:3000
    depends_on:
      - jellystat-db

# Want more!? https://github.com/awesome-jellyfin/awesome-jellyfin
