services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_PUBLISHED_SERVER_URL} #optional
    volumes:
      - ${CONFIG_BASE}/jellyfin:/config
      - ${MEDIA_PATH}:/mnt/media
    devices:
      - /dev/dri:/dev/dri #Use for Intel QuickSync
    ports:
      - ${JELLYFIN_PORT}:8096
      - ${JELLYFIN_DISCOVERY_UDP}:7359/udp #Service Discovery
      - ${JELLYFIN_DLNA_UDP}:1900/udp #Client Discovery
    restart: unless-stopped
# Remove the Jellyfin service if installed directly on system.

  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_BASE}/jellyseerr:/app/config
    ports:
      - ${JELLYSEERR_PORT}:5055
    restart: unless-stopped

  jellystat-db:
    image: postgres:15.2
    container_name: jellystat-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${JELLYSTAT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${JELLYSTAT_POSTGRES_PASSWORD}
    volumes:
      - ${CONFIG_BASE}/jellystat/postgres:/var/lib/postgresql/data

  jellystat:
    image: cyfershepard/jellystat:latest
    container_name: jellystat
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${JELLYSTAT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${JELLYSTAT_POSTGRES_PASSWORD}
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: ${JELLYSTAT_JWT_SECRET}
      TZ: ${TZ}
    volumes:
      - ${CONFIG_BASE}/jellystat/backup-data:/app/backend/backup-data
    ports:
      - ${JELLYSTAT_PORT}:3000
    depends_on:
      - jellystat-db

# Want more!? https://github.com/awesome-jellyfin/awesome-jellyfin
